### ISSUE TITLE
NotImplementedError when calling xml.sax.parse

### ISSUE THREAD

**Issue by wese-da** [IronLanguages/ironpython3#1279]
When calling the function xml.sax.parse, IronPython throws a NotImplementedError.

Here is a snippet of the code I tried to run (the full code is part of the [SUMO project](https://github.com/eclipse/sumo/) and can be viewed under [this link](https://github.com/eclipse/sumo/blob/main/tools/sumolib/net/__init__.py) (line 798 ff.)):

```
def readNet(filename, **others):
    netreader = NetReader(**others)
    try:
        parse(gzip.open(filename), netreader)
    except IOError:
        parse(filename, netreader)
    return netreader.getNet()
```

NetReader is derived of xml.sax.handler.ContentHandler.

The error stack:
```
Traceback (most recent call last):
  File "runsingle.py", line 77, in <module>
  File "C:\Users\hoss_da\src\simo\projects\junction_control_comparison2\scenario\__init__.py", line 17, in __getattr__
  File "C:\Users\hoss_da\src\simo\projects\junction_control_comparison2\scenario\augsburg\__init__.py", line 45, in <module>
  File "C:\Users\hoss_da\src\simo\projects\junction_control_comparison2\common.py", line 802, in initScenarioModule
  File "C:\Users\hoss_da\src\simo\projects\junction_control_comparison2\common.py", line 439, in build_dir_to_lanes
  File "C:\sumo\tools\sumolib\net\__init__.py", line 814, in readNet
  File "C:\Program Files\IronPython 2.7\Lib\xml\sax\__init__.py", line 33, in parse
  File "C:\Program Files\IronPython 2.7\Lib\xml\sax\expatreader.py", line 109, in parse
  File "C:\Program Files\IronPython 2.7\Lib\xml\sax\expatreader.py", line 310, in reset
NotImplementedError: The method or operation is not implemented.
```

I tried running this under both IronPython 2.7.11.0 and 3.4.0.0 with identical results.

**Comment by slozier** [comment]
Thanks for the report.

It looks like I can unblock `xml.sax.parse` by adding some dummy functions instead of throwing (https://github.com/IronLanguages/ironpython3/pull/1280). I think this might be enough to enable your scenario, however I'm not sure...

Could you try editing the `Lib/xml/sax/expatreader.py` to remove the calls to `SetBase` and `SetParamEntityParsing` to see if it works:
https://github.com/IronLanguages/ironpython3/blob/01afd61229bfa4f7f81260055aa073c2c88b71ab/Src/StdLib/Lib/xml/sax/expatreader.py#L114
https://github.com/IronLanguages/ironpython3/blob/01afd61229bfa4f7f81260055aa073c2c88b71ab/Src/StdLib/Lib/xml/sax/expatreader.py#L291-L292

**Comment by wese-da** [comment]
Hi,

thank you for your fast reply. Removing these two calls in `Lib/xml/sax/expatreader.py` did indeed solve the issue I had. The xml files could be parsed correctly and everything else runs as expected.

**Comment by slozier** [comment]
Ok great, I'll make the changes to the codebase so that it will work with the next release.
