### ISSUE TITLE
Inconsistent exceptions when indexing multi-dimensional Array

### ISSUE THREAD

**Issue by BCSharp** [IronLanguages/ironpython3#1324]
### Description

Providing invalid indices for a multi-dimensional CLI `Array` may result in either `TypeError`, `IndexError`, or `ValueError`.

### Example

```python
>>> from System import Array
>>> rank3arr = Array[int](1, 1, 1)
>>> rank3arr[0, 0] 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: bad dimensions for array, got 2 expected 3
>>> rank3arr[0, 0, 0, 0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: Array does not have that many dimensions.
>>> rank3arr[0, 'a']    
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected int, got str
>>> rank3arr[0, 0, 'a']    
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected int, got str
>>> rank3arr[0, 0, 0, 'a']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected int, got str
>>> rank3arr[0, 0, 0, 0, 'a']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: Array does not have that many dimensions.
```

The question is, what would be a consistent error type?

In CPython, an invalid type of the index for, e.g. a list results in `TypeError`. However, lists are not multidimensional. For comparison, I use `memoryview`. It will always raise `TypeError` or `NotImplementedError`:

```python
>>> rank3mv = memoryview(b"\0").cast('b', shape=(1, 1, 1))
>>> rank3mv[0, 0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NotImplementedError: sub-views are not implemented
>>> rank3mv[0, 0, 0, 0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot index 3-dimension view with 4-element tuple
>>> rank3mv[0, 'a']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: memoryview: invalid slice key
>>> rank3mv[0, 0, 'a']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: memoryview: invalid slice key
>>> rank3mv[0, 0, 0, 'a']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: memoryview: invalid slice key
>>> rank3mv[0, 0, 0, 0, 'a']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: memoryview: invalid slice key
```

In NumPy, the above examples (except for fewer dimensions, which is allowed in NumPy) result in `IndexError`:

```python
>>> import numpy as np
>>> rank3arr = np.array(1).reshape((1, 1, 1))
>>> rank3arr
array([[[1]]])
>>> rank3arr[0, 0]
array([1])
>>> rank3arr[0, 0, 0, 0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed
>>> rank3arr[0, 'a']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
>>> rank3arr[0, 0, 'a']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
>>> rank3arr[0, 0, 0, 'a']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
>>> rank3arr[0, 0, 0, 0, 'a']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

### Proposal

In all cases above report consistently one type of error. Personally I like NumPy's approach of always reporting `IndexError`, but  always reporting `TypeError` seems good enough and probably is easier to implement.

**Comment by slozier** [comment]
I guess I'm fine with either - this is probably the sort of edge case that's actually a bug and not something the user wants to catch anyway. I assume having the correct types/dimensions but indexing out of range will still be an `IndexError`?

**Comment by BCSharp** [comment]
> I assume having the correct types/dimensions but indexing out of range will still be an `IndexError`?

Yes, out-of-range index value raises `IndexError` in all cases (IronPython, CPython, and NumPy) so it should stay so.
