### ISSUE TITLE
macOS: "LookupError: unknown encoding: cp0" when starting ipy

### ISSUE THREAD

**Issue by strongly-typed** [IronLanguages/ironpython3#1527]
When starting `ipy` on MacOS I get `LookupError: unknown encoding: cp0`.

I compiled IronPython for Mac from source as I did not find any binary releases for IronPython (homebrew?)

```zsh
➜  ironpython3 git:(35cc2274) ✗ pwsh make.ps1 -frameworks net6.0 debug
```

```zsh
➜  ironpython3 git:(35cc2274) ✗ ./bin/Debug/net6.0/ipy
Traceback (most recent call last):
  File "<string>", line 1567, in load_module
  File "<string>", line 596, in _load_module_shim
  File "<string>", line 1210, in load
  File "<string>", line 1190, in _load_unlocked
  File "<string>", line 1119, in _exec
  File "<string>", line 1461, in exec_module
  File "<string>", line 539, in _check_name_wrapper
  File "<string>", line 321, in _call_with_frames_removed
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 564, in <module>
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 550, in main
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 281, in addusersitepackages
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 257, in getusersitepackages
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 247, in getuserbase
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/sysconfig.py", line 595, in get_config_var
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/sysconfig.py", line 575, in get_config_vars
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/_osx_support.py", line 393, in customize_config_vars
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/_osx_support.py", line 135, in _supports_universal_builds
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/_osx_support.py", line 103, in _get_system_version
LookupError: unknown encoding: cp0IronPython 3.4.0b1 DEBUG (3.4.0.0010)
[.NETCoreApp,Version=v6.0 on .NET 6.0.7 (64-bit)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

When printing out the current encoding, `utf_8` is returned:

```
➜  ironpython3 git:(35cc2274) ✗ bin/Debug/net6.0/ipy -c "import sys; print('The enncoding is='+sys.stdin.encoding)"
Traceback (most recent call last):
  File "<string>", line 1567, in load_module
  File "<string>", line 596, in _load_module_shim
  File "<string>", line 1210, in load
  File "<string>", line 1190, in _load_unlocked
  File "<string>", line 1119, in _exec
  File "<string>", line 1461, in exec_module
  File "<string>", line 539, in _check_name_wrapper
  File "<string>", line 321, in _call_with_frames_removed
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 564, in <module>
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 550, in main
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 281, in addusersitepackages
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 257, in getusersitepackages
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 247, in getuserbase
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/sysconfig.py", line 595, in get_config_var
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/sysconfig.py", line 575, in get_config_vars
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/_osx_support.py", line 393, in customize_config_vars
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/_osx_support.py", line 135, in _supports_universal_builds
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/_osx_support.py", line 103, in _get_system_version
LookupError: unknown encoding: cp0The enncoding is=utf_8
```

Looking into the code reveals that `f = open('/System/Library/CoreServices/SystemVersion.plist')` is raising the error.

```
➜  ironpython3 git:(35cc2274) ✗ cat /System/Library/CoreServices/SystemVersion.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ProductBuildVersion</key>
	<string>19H2026</string>
	<key>ProductCopyright</key>
	<string>1983-2022 Apple Inc.</string>
	<key>ProductName</key>
	<string>Mac OS X</string>
	<key>ProductUserVisibleVersion</key>
	<string>10.15.7</string>
	<key>ProductVersion</key>
	<string>10.15.7</string>
	<key>iOSSupportVersion</key>
	<string>13.6</string>
</dict>
</plist>
```

```
➜  ironpython3 git:(35cc2274) ✗ file /System/Library/CoreServices/SystemVersion.plist
/System/Library/CoreServices/SystemVersion.plist: XML 1.0 document text, ASCII text
```

Reading this file with the default encoding yields to the error:

```
>>> f = open('/System/Library/CoreServices/SystemVersion.plist')
>>> print(f.readlines())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
LookupError: unknown encoding: cp0
>>> f = open('/System/Library/CoreServices/SystemVersion.plist', encoding='utf-8')
>>> print(f.readlines())
['<?xml version="1.0" encoding="UTF-8"?>\n', '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n', '<plist version="1.0">\n', '<dict>\n', '\t<key>ProductBuildVersion</key>\n', '\t<string>19H2026</string>\n', '\t<key>ProductCopyright</key>\n', '\t<string>1983-2022 Apple Inc.</string>\n', '\t<key>ProductName</key>\n', '\t<string>Mac OS X</string>\n', '\t<key>ProductUserVisibleVersion</key>\n', '\t<string>10.15.7</string>\n', '\t<key>ProductVersion</key>\n', '\t<string>10.15.7</string>\n', '\t<key>iOSSupportVersion</key>\n', '\t<string>13.6</string>\n', '</dict>\n', '</plist>\n']
```

Setting `PYTHONIOENCODING` did not change the behavior:
```
➜  ironpython3 git:(35cc2274) ✗ PYTHONIOENCODING=utf_8 bin/Debug/net6.0/ipy
Traceback (most recent call last):
  File "<string>", line 1567, in load_module
  File "<string>", line 596, in _load_module_shim
  File "<string>", line 1210, in load
  File "<string>", line 1190, in _load_unlocked
  File "<string>", line 1119, in _exec
  File "<string>", line 1461, in exec_module
  File "<string>", line 539, in _check_name_wrapper
  File "<string>", line 321, in _call_with_frames_removed
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 564, in <module>
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 550, in main
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 281, in addusersitepackages
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 257, in getusersitepackages
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 247, in getuserbase
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/sysconfig.py", line 595, in get_config_var
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/sysconfig.py", line 575, in get_config_vars
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/_osx_support.py", line 393, in customize_config_vars
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/_osx_support.py", line 135, in _supports_universal_builds
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/_osx_support.py", line 103, in _get_system_version
LookupError: unknown encoding: cp0IronPython 3.4.0b1 DEBUG (3.4.0.0010)
[.NETCoreApp,Version=v6.0 on .NET 6.0.7 (64-bit)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
➜  ironpython3 git:(35cc2274) ✗ PYTHONIOENCODING=utf-8 bin/Debug/net6.0/ipy
Traceback (most recent call last):
  File "<string>", line 1567, in load_module
  File "<string>", line 596, in _load_module_shim
  File "<string>", line 1210, in load
  File "<string>", line 1190, in _load_unlocked
  File "<string>", line 1119, in _exec
  File "<string>", line 1461, in exec_module
  File "<string>", line 539, in _check_name_wrapper
  File "<string>", line 321, in _call_with_frames_removed
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 564, in <module>
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 550, in main
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 281, in addusersitepackages
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 257, in getusersitepackages
  File "/Users/sascha/Dev/ironpython3/bin/Debug/net6.0/../../../Src/StdLib/Lib/site.py", line 247, in getuserbase
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/sysconfig.py", line 595, in get_config_var
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/sysconfig.py", line 575, in get_config_vars
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/_osx_support.py", line 393, in customize_config_vars
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/_osx_support.py", line 135, in _supports_universal_builds
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/_osx_support.py", line 103, in _get_system_version
LookupError: unknown encoding: cp0IronPython 3.4.0b1 DEBUG (3.4.0.0010)
[.NETCoreApp,Version=v6.0 on .NET 6.0.7 (64-bit)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Forcefully editing [`_osx_support.py`](https://github.com/IronLanguages/ironpython3/blob/master/Src/StdLib/Lib/_osx_support.py#L96) to open the file with `utf-8` works:
```
f = open('/System/Library/CoreServices/SystemVersion.plist', encoding='utf-8')
```

**Any suggested work-around or fix?**

## Environment

```zsh
➜  ~ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.302/

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by strongly-typed** [comment]
The error continuous when running any command:

```
➜  ~ ~/Dev/ironpython3/bin/Debug/net6.0/ipy -c "import platform; platform.system()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/platform.py", line 1083, in system
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/platform.py", line 1049, in uname
  File "/Users/sascha/Dev/ironpython3/Src/StdLib/Lib/platform.py", line 806, in _syscmd_uname
LookupError: unknown encoding: cp0
```

Unfortunately, there is no way to add an `encoding` parameter to `os.popen` in [`platform.py`](https://github.com/IronLanguages/ironpython3/blob/master/Src/StdLib/Lib/platform.py#L803).

What is the root cause of this?

**Comment by slozier** [comment]
Can you run `import _locale; print(_locale._getdefaultlocale())` to see what that outputs? I think the 2nd value in the tuple is what's used on open (so it'll probably show up as `cp0` for you). As for why that value ends up as `cp0` I have no idea - the code appears to use `CultureInfo.CurrentCulture.TextInfo.ANSICodePage` so I guess that's 0 for some reason... Can you also try the same thing with CPython to see what that outputs?

**Comment by BCSharp** [comment]
Also, can you print out the content of the environment variable `__CF_USER_TEXT_ENCODING`?

**Comment by strongly-typed** [comment]
I didn't run it with underscores. Is this a typo or a special module?

```
➜  ~ python3.10 -c "import locale; print(locale.getdefaultlocale())"
(None, 'UTF-8')
➜  ~ Dev/ironpython3/bin/Debug/net6.0/ipy -c "import locale; print(locale.getdefaultlocale())"
('en_DE', 'cp0')
➜  ~ echo $__CF_USER_TEXT_ENCODING
0x0:0:0
```

**Comment by strongly-typed** [comment]
Tried to change this
```
➜  ~ export __CF_USER_TEXT_ENCODING="0x08000100:0:0:0"
➜  ~ Dev/ironpython3/bin/Debug/net6.0/ipy -c "import locale; print(locale.getdefaultlocale())"
('en_DE', 'cp0')
➜  ~ echo $__CF_USER_TEXT_ENCODING
0x08000100:0:0:0
➜  ~ cat ~/.CFUserTextEncoding
0x08000100:0
```

**Comment by slozier** [comment]
Managed to reproduce like this:
```pycon
>>> import System
>>> System.Globalization.CultureInfo.CurrentCulture = System.Globalization.CultureInfo("en-DE")
>>> import locale; locale.getdefaultlocale()
('en_DE', 'cp0')
>>> import platform; platform.system()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/slozier/ironpython3/Src/StdLib/Lib/platform.py", line 1068, in system
  File "/home/slozier/ironpython3/Src/StdLib/Lib/platform.py", line 1034, in uname
  File "/home/slozier/ironpython3/Src/StdLib/Lib/platform.py", line 791, in _syscmd_uname
LookupError: unknown encoding: cp0
```

**Comment by strongly-typed** [comment]
OK, I never set up my computer in German. I always choose "en-EN" from the very beginning. Maybe macOS is aware of my location on earth and tries to set up something ...

You are right, `System.Globalization.CultureInfo.CurrentCulture` is set to `en-DE` on my machine.

```
➜  ~ Dev/ironpython3/bin/Debug/net6.0/ipy
IronPython 3.4.0b1 DEBUG (3.4.0.0010)
[.NETCoreApp,Version=v6.0 on .NET 6.0.7 (64-bit)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import System
>>> print(System.Globalization.CultureInfo.CurrentCulture)
en-DE
```

If I change this, I get it working.

```
➜  ~ Dev/ironpython3/bin/Debug/net6.0/ipy
IronPython 3.4.0b1 DEBUG (3.4.0.0010)
[.NETCoreApp,Version=v6.0 on .NET 6.0.7 (64-bit)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import System
>>> System.Globalization.CultureInfo.CurrentCulture = System.Globalization.CultureInfo("en-EN")
>>> import locale; locale.getdefaultlocale()
('en_EN', 'cp1252')
>>> import platform; platform.system()
'Darwin'
```

1. How to set `CurrentCulture` to `en-EN` globally and statically?
2. How fix it for `en-DE`?

I am mostly interested in 1. ;-)

**Comment by strongly-typed** [comment]
OK, I solved 1.:

```
➜  ~ Dev/ironpython3/bin/Debug/net6.0/ipy
IronPython 3.4.0b1 DEBUG (3.4.0.0010)
[.NETCoreApp,Version=v6.0 on .NET 6.0.7 (64-bit)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import System
>>> print(System.Globalization.CultureInfo.CurrentCulture)
en-US
```
For whatever reason (autodetection?) the region was different to "US" which lead to the `en-DE`. Now I set it to "US" and IronPython works.

<img width="666" alt="Screen Shot 2022-08-05 at 20 49 21" src="https://user-images.githubusercontent.com/1626990/183142326-fe28f80d-d238-4ebe-aa39-1a6876a6b4fe.png">

So IronPython is only usable in the US on Macs .-)

**Comment by BCSharp** [comment]
Just for the record: another way of changing this in your shell session is by setting environment variable `LANG` to `en_US.UTF-8`. The code before the dot should be a valid combination of language-country. `en_CA.UTF-8` also works, if you prefer to relocate to Canada rather than the US ;-) `de_DE.UTF-8` also works and strangely `de_US.UTF-8`, or even `de_JP.UTF-8`

I suppose we could do something similar for `en`: if the country code is not being recognized as a valid choice for `en`, `US` is the fallback.

**Comment by slozier** [comment]
> So IronPython is only usable in the US on Macs .-)

Not sure what .NET is thinking - there are only a handful of two letter codes that don't work (on Linux):
```py
for x in range(26):
    for y in range(26):
        System.Globalization.CultureInfo.CurrentCulture = System.Globalization.CultureInfo("en-{}{}".format(chr(x+ord('A')), chr(y+ord('A'))))
        l = locale.getdefaultlocale()
        if l[1] != "cp1252":
            print(l)
```
```
('en_AT', 'cp0')
('en_BI', 'cp0')
('en_CH', 'cp0')
('en_CY', 'cp0')
('en_DE', 'cp0')
('en_DK', 'cp0')
('en_FI', 'cp0')
('en_IL', 'cp0')
('en_NL', 'cp0')
('en_SE', 'cp0')
('en_SI', 'cp0')
```

**Comment by strongly-typed** [comment]
> Not sure what .NET is thinking - there are only a handful of two letter codes that don't work (on Linux):

Same on macOS:

```
('en_AT', 'cp0')
('en_BI', 'cp0')
('en_CH', 'cp0')
('en_CY', 'cp0')
('en_DE', 'cp0')
('en_DK', 'cp0')
('en_FI', 'cp0')
('en_IL', 'cp0')
('en_NL', 'cp0')
('en_SE', 'cp0')
('en_SI', 'cp0')
```

Very special countries ./ I would love to relocate to Canada .-)

**Comment by BCSharp** [comment]
> > Not sure what .NET is thinking - there are only a handful of two letter codes that don't work (on Linux):
> 
> Same on macOS:

Same on Windows. Mono has a different set of reactions to unusual combinations.

**Comment by slozier** [comment]
Here's the big table where .NET gets its info: https://source.dot.net/#System.Private.CoreLib/IcuLocaleData.cs,99eb5fb42808f867

**Comment by BCSharp** [comment]
> ```
> LookupError: unknown encoding: cp0
> ```

Regardless of what .NET is thinking, `cp0` is a legitimate encoding name, and on macOS/Linus should have resolved to UTF-8. And normally it does:
```
>>> 'abcü'.encode('cp0')
b'abc\xc3\xbc'
>>> 'abcü'.encode('utf-8')
b'abc\xc3\xbc'
```

However, with `open`, a different code path is followed, so apparently it doesn't work as expected. I remember @slozier and I have discussed it on at least one occasion, but now I can't find the reference.

**Comment by slozier** [comment]
@BCSharp Maybe https://github.com/IronLanguages/ironpython3/issues/906?

**Comment by BCSharp** [comment]
Yup. That's it.

**Comment by slozier** [comment]
I guess the fix is probably to not return the codepage of `CultureInfo.CurrentCulture.TextInfo.ANSICodePage`. This value doesn't match up with what CPython returns (the ACP on Windows) and is obviously wrong on macOS/Linux (where `utf-8` is probably what's expected). I think the solution is probably to use the `Encoding.GetEncoding(0).CodePage` value instead. Will do a PR shortly.

> Regardless of what .NET is thinking, `cp0` is a legitimate encoding name, and on macOS/Linus should have resolved to UTF-8.

Looks like `cp0` is legitimate on the .NET side of things (used by `str.encode`), but not on the Python side of things (used by `open`). CPython also doesn't like `cp0` on `encode`.

**Comment by BCSharp** [comment]
> I guess the fix is probably to not return the codepage of `CultureInfo.CurrentCulture.TextInfo.ANSICodePage`. This value doesn't match up with what CPython returns (the ACP on Windows) and is obviously wrong on macOS/Linux (where `utf-8` is probably what's expected).

I agree that the current implementation of `PythonLocale.PreferredEncoding` is incorrect.

> I think the solution is probably to use the `Encoding.GetEncoding(0).CodePage` value instead.

I wonder if `Encoding.GetEncoding(0).Name` wouldn't work better. However, this still depends on .NET deciding what the default encoding is, which does not necessarily correspond to CPython's behaviour, which seems to pull the encoding from `LC_ALL`, `LC_CTYPE`, `LANG` and `LANGUAGE`, in that order. If the name is invalid (or absent), only then does CPython fall back to UTF-8 (on non-Windows systems).

**Comment by slozier** [comment]
> > I think the solution is probably to use the `Encoding.GetEncoding(0).CodePage` value instead.
> 
> I wonder if `Encoding.GetEncoding(0).Name` wouldn't work better. However, this still depends on .NET deciding what the default encoding is, which does not necessarily correspond to CPython's behaviour, which seems to pull the encoding from `LC_ALL`, `LC_CTYPE`, `LANG` and `LANGUAGE`, in that order. If the name is invalid (or absent), only then does CPython fall back to UTF-8 (on non-Windows systems).

Not seeing an `Encoding.Name` property? I ran a bunch of tests on Windows with `cp + Encoding.GetEncoding(0).CodePage` and it seems to match what CPython gives. Unfortunately it broke things on Linux/macOS since the StdLib only allows using `cp65001` on Windows (it only changed to being an alias for utf-8 in 3.8).

Another potential issue is someone might be able to register an `EncodingProvider` which returns whatever for codepage 0. Might be better to rely directly on `GetACP` on Windows and what you describe on macOS/Linux (or just hardcode UTF-8 for now which is better than what we're doing anyway)?

**Comment by BCSharp** [comment]
> Not seeing an `Encoding.Name` property?

Meant `WebName`. Not a big deal, as long as it works. 

> Might be better to rely directly on `GetACP` on Windows and what you describe on macOS/Linux (or just hardcode UTF-8 for now which is better than what we're doing anyway)?

That's what I meant with relying on .NET. From the perspective of addressing this particular issue report, hardcoding UTF-8 is good enough, I think. A more accurate implementation can be done under a separate issue.

**Comment by slozier** [comment]
Added https://github.com/IronLanguages/ironpython3/issues/1529 for the preferred encoding issue.
