### ISSUE TITLE
Ironpython reports  "No module named 'stat'" when failing importing os module 

### ISSUE THREAD

**Issue by xiaxinmeng** [IronLanguages/ironpython3#1606]
The release mode of ironpython fails to import 'os' module. (It can import other modules like 'sys'. So I guess I have installed ironpython correctly. This may be buggy.) Besides, it is weird that Ironpython fails importing 'os' module but the error message is no module name "stat''.  By the way, under debug mode, ironpython can import os correctly.

Error message.
```
[.NETCoreApp,Version=v6.0 on .NET 6.0.11 (64-bit)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 540, in _check_name_wrapper
  File "<string>", line 1565, in load_module
  File "<string>", line 597, in _load_module_shim
  File "<string>", line 1208, in load
  File "<string>", line 1188, in _load_unlocked
  File "<string>", line 1117, in _exec
  File "<string>", line 1459, in exec_module
  File "<string>", line 322, in _call_with_frames_removed
  File "/home/xxm/Desktop/IFuzzer/experiment_on_different_interpreter/ironpython/ironpython3/bin/Release/net6.0/lib/os.py", line 27, in <module>
ImportError: No module named 'stat'
```

Expected behavior:
1. ironpython can import 'os' module correctly.
2. even if ironpython cannot import os module, the error message should be "ImportError: No module named 'os'".

I install ironpython master branch on Ubuntu 18.04 by the following step:
1. git clone https://github.com/IronLanguages/ironpython3.git
3. typing "./make.ps1"

**Comment by slozier** [comment]
`stat` is part of the standard library and the build process does not copy the standard library to the output folder. As noted in the [Building IronPython3](https://github.com/IronLanguages/ironpython3/blob/master/Documentation/building.md#running) document, to run from the Release folder you should set the `IRONPYTHONPATH` environment variable to point to the folder containing the standard library `<path to ironpython3 repo>/Src/StdLib/Lib`.

Duplicate of https://github.com/IronLanguages/ironpython3/issues/821.

**Comment by xiaxinmeng** [comment]
I see now. Thank you very much.
