### ISSUE TITLE
Setting attribute to 'self' in unittest.mock.patch crashes ironpython

### ISSUE THREAD

**Issue by xiaxinmeng** [IronLanguages/ironpython3#1609]
In the following example, we set the attribute 'new_callable' of unittest.mock.patch as 'self'. then ironpython crashes.

test.py 
```

from unittest.mock import patch
from unittest import TestCase, main

class Foo:
    properties = []

class FooTest(TestCase):

    def setUp(self):
        patcher = patch(f'{__name__}.Foo.properties', new_callable=self)
        patcher.start()

    def test_foo(self):
        pass

if __name__ == '__main__':
    main()
```

Error message:
```
>>'ironpython/ironpython3/bin/Debug/net6.0/ipy' test.py

....
   at Microsoft.Scripting.Hosting.Shell.CommandLine.Run()
   at IronPython.Hosting.PythonCommandLine.Run()
   at Microsoft.Scripting.Hosting.Shell.CommandLine.Run(Microsoft.Scripting.Hosting.ScriptEngine, Microsoft.Scripting.Hosting.Shell.IConsole, Microsoft.Scripting.Hosting.Shell.ConsoleOptions)
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.RunCommandLine()
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.ExecuteInternal()
   at PythonConsoleHost.ExecuteInternal()
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.Execute()
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.Run(System.String[])
   at PythonConsoleHost.Main(System.String[])
Aborted (core dumped)

```

System info:
ironpython3-debug(main branch):IronPython 3.4.0b1 DEBUG (3.4.0.0010)[.NETCoreApp,Version=v6.0 on .NET 6.0.11 (64-bit)] on linux
operating system: Ubuntu 18.04.6 LTS

**Comment by slozier** [comment]
Recursion checks are off by default in IronPython, see the Recursion section in [Differences from CPython](https://github.com/IronLanguages/ironpython3/blob/master/Documentation/differences-from-c-python.md#recursion). You need to run with the `-X MaxRecursion=100` argument to get the expected behavior.
