### ISSUE TITLE
Specific string format causes crashes

### ISSUE THREAD

**Issue by xiaxinmeng** [IronLanguages/ironpython3#1614]
See the following example. We  print the '{0:5X} {0:c}'.format(x), then ironpython crashes.

test.py
```
for x in range(32,50):
    print('{0:5X} {0:c}'.format(x))
```

Error message
```
>>'ironpython/ironpython3/bin/Debug/net6.0/ipy' test.py
...
DLR/Src/Microsoft.Dynamic/Hosting/Shell/ConsoleHost.cs:line 321
   at PythonConsoleHost.ExecuteInternal() in /home/xxm/Desktop/IFuzzer/experiment_on_different_interpreter/ironpython/ironpython3/Src/IronPythonConsole/Console.cs:line 165
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.Execute() in /home/xxm/Desktop/IFuzzer/experiment_on_different_interpreter/ironpython/ironpython3/Src/DLR/Src/Microsoft.Dynamic/Hosting/Shell/ConsoleHost.cs:line 299
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.Run(String[] args) in /home/xxm/Desktop/IFuzzer/experiment_on_different_interpreter/ironpython/ironpython3/Src/DLR/Src/Microsoft.Dynamic/Hosting/Shell/ConsoleHost.cs:line 197
   at PythonConsoleHost.Main(String[] args) in /home/xxm/Desktop/IFuzzer/experiment_on_different_interpreter/ironpython/ironpython3/Src/IronPythonConsole/Console.cs:line 199
Aborted (core dumped)
```

Behaviors on CPython 3.9.1:
```
   20  
   21 !
   22 "
   23 #
   24 $
   25 %
   26 &
   27 '
   28 (
   29 )
   2A *
   2B +
   2C ,
   2D -
   2E .
   2F /
   30 0
   31 1
```

System info:
ironpython3-debug(main branch):IronPython 3.4.0b1 DEBUG (3.4.0.0010)[.NETCoreApp,Version=v6.0 on .NET 6.0.11 (64-bit)] on linux
operating system: Ubuntu 18.04.6 LTS

**Comment by slozier** [comment]
Thanks! Works properly in release mode but hits an assertion error in debug mode.
