### ISSUE TITLE
Long string in Tokenlist of email.policy crashes Ironpython

### ISSUE THREAD

**Issue by xiaxinmeng** [IronLanguages/ironpython3#1617]
The following code crashes Ironpython at  "ValueTerminal('x'*76, 'crash here')". (Ironpython does not crash if taking 'x'*75 as arguments). This code works well on CPython.

```
from email._header_value_parser import *
import email.policy
tl = TokenList([
        ValueTerminal('x', 'work well here'),
        WhiteSpaceTerminal(' ', 'work well here'),
        ValueTerminal('x', 'work well here'),
        ValueTerminal('x'*76, 'crash here'),
])
tl.fold(policy=email.policy.default)

```

Error message:
```
>>'ironpython/ironpython3/bin/Debug/net6.0/ipy' test.py
.........
reter.InterpretedFrame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon)
   at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Microsoft.Scripting.Runtime.Scope)
   at IronPython.Compiler.RuntimeScriptCode.Run(Microsoft.Scripting.Runtime.Scope)
   at IronPython.Hosting.PythonCommandLine.RunFileWorker(System.String)
   at IronPython.Hosting.PythonCommandLine.RunFile(System.String)
   at Microsoft.Scripting.Hosting.Shell.CommandLine.Run()
   at IronPython.Hosting.PythonCommandLine.Run()
   at Microsoft.Scripting.Hosting.Shell.CommandLine.Run(Microsoft.Scripting.Hosting.ScriptEngine, Microsoft.Scripting.Hosting.Shell.IConsole, Microsoft.Scripting.Hosting.Shell.ConsoleOptions)
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.RunCommandLine()
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.ExecuteInternal()
   at PythonConsoleHost.ExecuteInternal()
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.Execute()
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.Run(System.String[])
   at PythonConsoleHost.Main(System.String[])
Aborted (core dumped)
```

System info:
ironpython3-debug(main branch):IronPython 3.4.0b1 DEBUG (3.4.0.0010)[.NETCoreApp,Version=v6.0 on .NET 6.0.11 (64-bit)] on linux
operating system: Ubuntu 18.04.6 LTS

**Comment by slozier** [comment]
Thanks for the report. Seems to be a bug in the standard library which was fixed in Python 3.6. The 3.6 branch does not have this issue so unless there's a specific use case for fixing it in 3.4 I'll close this issue.
