### ISSUE TITLE
future feature is not defined

### ISSUE THREAD

**Issue by AtFy** [IronLanguages/ironpython3#1781]
### Prerequisites
* [ ] Are you running the latest version? - 3.4.1
* [ ] Are you reporting to the correct repository? - yes.
* [ ] Did you perform a cursory search? - yes. I found out that this issue appears because "the import of __future__ annotations is available starting with Python 3.7." And, since IronPython runs on 3.4 it's not working...I guess?

### Description
I have a python script wirtten on Python 3.9.
When I try to run it in my application I get this 

 `Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.Scripting.SyntaxErrorException: future feature is not defined:annotations
         at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
         at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
         at IronPython.Runtime.FunctionCaller1.Call1(CallSite site, CodeContext context, Object func, T0 arg0)
         at IronPython.Runtime.Method.MethodBinding.SelfTarget(CallSite site, CodeContext context, Object target)
         at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
         at IronPython.Runtime.FunctionCaller.Call0(CallSite site, CodeContext context, Object func)
         at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
         at IronPython.Runtime.FunctionCaller2.Call2(CallSite site, CodeContext context, Object func, T0 arg0, T1 arg1)
         at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
         at CallSite.Target(Closure, CallSite, CodeContext, Object, Object, Object)
         at IronPython.Runtime.Method.MethodBinding1.SelfTarget(CallSite site, CodeContext context, Object target, T0 arg0)
         at IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
         at Microsoft.Scripting.Interpreter.FuncCallInstruction5.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.LightLambda.Run7[T0,T1,T2,T3,T4,T5,T6,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
         at System.Dynamic.UpdateDelegates.UpdateAndExecute6[T0,T1,T2,T3,T4,T5,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
         at Microsoft.Scripting.Interpreter.FuncCallInstruction9.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.LightLambda.Run7[T0,T1,T2,T3,T4,T5,T6,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
         at Microsoft.Scripting.Interpreter.DynamicInstruction7.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.LightLambda.Run5[T0,T1,T2,T3,T4,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
         at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
         at IronPython.Runtime.FunctionCaller2.Call2(CallSite site, CodeContext context, Object func, T0 arg0, T1 arg1)
         at IronPython.Runtime.Method.MethodBinding1.SelfTarget(CallSite site, CodeContext context, Object target, T0 arg0)
         at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
         at Microsoft.Scripting.Interpreter.FuncCallInstruction6.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
         at IronPython.Runtime.PythonContext.Call(CodeContext context, Object func, Object arg0)
         at IronPython.Runtime.Importer.FindAndLoadModuleFromImporter(CodeContext context, Object importer, String fullName, PythonList path, Object& ret)
         at IronPython.Runtime.Importer.TryLoadMetaPathModule(CodeContext context, String fullName, PythonList path, Object& ret)
         at IronPython.Runtime.Importer.ImportTopAbsolute(CodeContext context, String name)
         at IronPython.Runtime.Importer.ImportModule(CodeContext context, Object globals, String modName, Boolean bottom, Int32 level)
         at IronPython.Modules.Builtin.__import__(CodeContext context, String name, Object globals, Object locals, Object fromlist, Int32 level)
         at Microsoft.Scripting.Interpreter.FuncCallInstruction7.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.LightLambda.Run8[T0,T1,T2,T3,T4,T5,T6,T7,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
         at IronPython.Runtime.Importer.ImportLightThrow(CodeContext context, String fullName, PythonTuple from, Int32 level)
         at IronPython.Runtime.Operations.PythonOps.ImportBottom(CodeContext context, String fullName, Int32 level)
         at Microsoft.Scripting.Interpreter.FuncCallInstruction4.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
         at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
         at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
         at IronPython.Compiler.PythonScriptCode.Run(Scope scope)
         at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
         at IronPython.Compiler.RuntimeScriptCode.Run(Scope scope)
         at Microsoft.Scripting.SourceUnit.Execute(Scope scope, ErrorSink errorSink)
         at Microsoft.Scripting.SourceUnit.Execute(Scope scope)
         at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
         at Microsoft.Scripting.Hosting.ScriptEngine.ExecuteFile(String path, ScriptScope scope)
         at AdsterraAutoReturn.Controllers.ProcessPubsCsvSetController.SendEmailsCreateDeals(String pubsCsv) in D:\AtFy\Dev\Projects\CSharp\AdsterraAutoReturn\AdsterraAutoReturn\Controllers\ProcessPubsCsvSetController.cs:line 59
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
`

### Steps to Reproduce

1. Create a Python 3.9 script with "from future import annotations"
2. Try to run it via .NET environment.

**Expected behavior:**
I simpy expect all the libraries to be imported correctly.

**Actual behavior:**
I got this error I've described.

### Version Information
* IronPython - 3.4.1
* .NET platform used  - .net
* Version of the .NET platform used - 7.0
* Operating system used - Windows 11 Pro
* Value of `sys.version`, from imported module `sys` - where do I find it?

**Comment by slozier** [comment]
`__future__.annotations` was added in Python 3.7 and so is not available in IronPython 3.4 (which is based on Python 3.4).

This is a duplicate of https://github.com/IronLanguages/ironpython3/issues/1675
