### ISSUE TITLE
Install setup.py

### ISSUE THREAD

**Issue by nalsandori** [IronLanguages/ironpython3#1794]
- setup.py
```python
from setuptools import setup
```

- windows 10> cmd
```bash
d:\> ipy setup.py install
```

- Result
```bash
...
c:\program files\Ironpython 3.4\lib\site.py, line 162, in addpackage
...
c:\program fIles\IronPython 3.4\lib\site.py, line 564, in <module>
Lookuperror: unknown encoding: cp949
```

- So, I modified code in site.py
```python
def addpackage(sitedir, name, known_paths):
    ...
    fullname = os.path.join(sitedir, name)
    try:
        f = open(fullname, "r")  #occured error
        #f = open(fullname, "r", encoding='utf8')
```
- It was good working when I added encoding='utf8'
- It is possible to set setlocale to utf8 without modifying the library?

**Comment by slozier** [comment]
Does this work?
> ipy -X utf8 setup.py install

**Comment by nalsandori** [comment]
- The command worked well
- I even checked that it was installed in test_package-py3.4.egg\site-package folder
- However, I have two questions
  1. When I try to import a package from ironpython Console, There is an Importerror: No module named
    ```python
    >>> import test
           Trackback (most recent call last):
            ImportError: No module named 'test'    
```
  2. How do I delete the package?
  ```batch
    c:\test>ipy -x utf8 pip uninstall test
    Uninstalling test_package:
      Would remove:
        c:\program files\ironpython 3.4\lib\site-packages\test_package-py3.4.egg
    Proceed (y/n)? Error: Exceptions
    Traceback (most recent call last):
      FIle "...\site-packages\pip\_internal\cli\base_command.py", line 178, in main status = self.run(options, args)
      ...
      File "...\pip\_internal\req\req_uninstall.py", line 425, in _allowed_to_proceed
        return ask('Proceed (y/n)? ', ('y', 'n')) == 'y'
      File "...\pip\_internal\utils\misc.py", line 183, in ask response = input(message)
    Lookyperror: unknown encoding: ks_c_5601_1987
```

**Comment by slozier** [comment]
For the import error I'm not sure. Looking at the uninstall error I guess you package is an `egg` file? Does it appear in your `sys.path`? For example:
```py
['.', 'C:\\Program Files\\IronPython 3.4\\lib', ..., 'C:\\Program Files\\IronPython 3.4\\lib\\site-packages', 'C:\\Program Files\\IronPython 3.4\\lib\\site-packages\\mytest-0.1-py3.4.egg']
```
I don't know much about `egg` files, but I think they're basically just `zip` files. Once they're in `sys.path` the import mechanism should be able to load them. It looks like this is normally done via `.pth` files...

For the package deletion, you could try: `ipy -m pip uninstall -y test` so it skips the input prompt (which has issues with encoding).
