### ISSUE TITLE
errors from IronPythonTestConsole should include python exception details

### ISSUE THREAD

**Issue by paweljasinski** [IronLanguages/ironpython3#42]
If a test case has a simple syntax error, there is no python stacktrace to track it down.

```
$ ./IronPythonTestConsole.exe  IronPythonTest -noh -labels -full -test:IronPythonTest.Cases.IronPythonCases.test_bool
Runtime Environment -
    OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
  .NET Version: 4.0.30319.18444

***** IronPythonTest.DLL
***** IronPythonCases
***** IronPythonTests
***** test_bool
Tests run: 1, Passed: 0, Errors: 1, Failures: 0, Inconclusive: 0
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
Elapsed time: 00:00:00.5840000

Errors and Failures:

1) test_bool (IronPythonTest.Cases.IronPythonCases.test_bool)
   Microsoft.Scripting.SyntaxErrorException : invalid syntax
   at Microsoft.Scripting.ErrorSink.Add(SourceUnit source, String message, SourceSpan span, Int32 errorCode, Severity severity)
   at IronPython.Compiler.Parser.ReportSyntaxError(Int32 start, Int32 end, String message, Int32 errorCode) in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 375
   at IronPython.Compiler.Parser.ReportSyntaxError(Int32 start, Int32 end, String message) in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 367
   at IronPython.Compiler.Parser.ReportSyntaxError(String message) in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 363
   at IronPython.Compiler.Parser.AddTrailers(Expression ret, Boolean allowGeneratorExpression) in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 2296
   at IronPython.Compiler.Parser.AddTrailers(Expression ret) in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 2255
   at IronPython.Compiler.Parser.ParsePower() in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 2141
   at IronPython.Compiler.Parser.ParseFactor() in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 2107
   at IronPython.Compiler.Parser.ParseExpr(Int32 precedence) in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 2070
   at IronPython.Compiler.Parser.ParseExpr() in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 2066
   at IronPython.Compiler.Parser.ParseComparison() in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 2024
   at IronPython.Compiler.Parser.ParseNotTest() in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 2018
   at IronPython.Compiler.Parser.ParseAndTest() in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 2001
   at IronPython.Compiler.Parser.ParseOrTest() in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 1983
   at IronPython.Compiler.Parser.ParseExpression() in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 1971
   at IronPython.Compiler.Parser.ParseTestListAsExpr() in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 2635
   at IronPython.Compiler.Parser.ParseExprStmt() in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 708
   at IronPython.Compiler.Parser.ParseSmallStmt() in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 531
   at IronPython.Compiler.Parser.ParseSimpleStmt() in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 453
   at IronPython.Compiler.Parser.ParseStmt() in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 447
   at IronPython.Compiler.Parser.ParseFileWorker(Boolean makeModule, Boolean returnValue) in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 3315
   at IronPython.Compiler.Parser.ParseFile(Boolean makeModule, Boolean returnValue) in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Compiler\Parser.cs:line 144
   at IronPython.Runtime.PythonContext.ParseAndBindAst(CompilerContext context) in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Runtime\PythonContext.cs:line 908
   at IronPython.Runtime.PythonContext.CompilePythonCode(SourceUnit sourceUnit, CompilerOptions options, ErrorSink errorSink) in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Runtime\PythonContext.cs:line 947
   at IronPython.Runtime.PythonContext.CompileSourceCode(SourceUnit sourceUnit, CompilerOptions options, ErrorSink errorSink) in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPython\Runtime\PythonContext.cs:line 956
   at Microsoft.Scripting.SourceUnit.Execute(Scope scope, ErrorSink errorSink)
   at IronPythonTest.Cases.CaseExecuter.GetResult(ScriptEngine engine, ScriptSource source) in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPythonTest\Cases\CaseExecuter.cs:line 75
   at IronPythonTest.Cases.CaseExecuter.GetScopeTest(TestInfo testcase) in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPythonTest\Cases\CaseExecuter.cs:line 70
   at IronPythonTest.Cases.CaseExecuter.RunTest(TestInfo testcase) in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPythonTest\Cases\CaseExecuter.cs:line 48
   at IronPythonTest.Cases.IronPythonCases.IronPythonTests(TestInfo testcase) in c:\cygwin64\home\rejap\github\ironpython3\Src\IronPythonTest\Cases\IronPythonCases.cs:line 24
```

**Comment by slide** [comment]
This has been implemented
