### ISSUE TITLE
missing _have_funtions in module _nt causes exception

### ISSUE THREAD

**Issue by paweljasinski** [IronLanguages/ironpython3#44]
```
$ ./ipy.exe -c 'print(1)'
Traceback (most recent call last):
  File "C:\cygwin64\home\rejap\github\ironpython3\Src\StdLib\Lib\site.py", line 72, in <module>
  File "C:\cygwin64\home\rejap\github\ironpython3\Src\StdLib\Lib\os.py", line 403, in <module>
NameError: global name 'supports_dir_fd' is not defined1
```

**Comment by slide** [comment]
Fixed via #134
