### ISSUE TITLE
subprocess.check_call is failing with a TypeError

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#482]
```Python
subprocess.check_call(sys.executable)
```
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\subprocess.py", line 553, in check_call
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\subprocess.py", line 538, in call
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\subprocess.py", line 901, in __exit__
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\subprocess.py", line 1161, in wait
TypeError: expected _subprocess_handle, got Extensible[]

**Comment by slozier** [comment]
Fixed by https://github.com/IronLanguages/ironpython3/pull/535
