### ISSUE TITLE
Some tests are failing via the test runner but not when run directly

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#489]
Both `AllCPython.test_dynamic` and `AllCPython.test_webbrowser` are passing when run directly using `ipy` but fail with the test runner. Figure out why.

**Comment by slozier** [comment]
Note that these will pass with `IsolationLevel=PROCESS`.

**Comment by slozier** [comment]
Also, `AllCPython.test_deque` (https://github.com/IronLanguages/ironpython3/pull/516).

**Comment by slide** [comment]
Can we turn on redirection of stdout/stderr?

**Comment by slozier** [comment]
For some reason I can't get test_webbrowser to fail locally, will try with a PR. Here are the other errors.

test_dynamic
---
```
Error Message:
 Traceback (most recent call last):
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\test_dynamic.py", line 143, in <module>
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\test_dynamic.py", line 139, in test_main
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1812, in run_unittest
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1787, in _run_suite
test.support.TestFailed: Traceback (most recent call last):
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 2029, in swap_item
    yield
NameError: name 'next' is not defined
```
```
Error Message:
 Traceback (most recent call last):
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\test_dynamic.py", line 143, in <module>
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\test_dynamic.py", line 139, in test_main
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1812, in run_unittest
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1787, in _run_suite
test.support.TestFailed: Traceback (most recent call last):
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\test_dynamic.py", line 126, in test_cannot_replace_builtins_dict_between_calls
    self.assertEqual(foo(), 3)
AssertionError: None != 3
```
test_deque
---

```
Error Message:
 Traceback (most recent call last):
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\test_deque.py", line 825, in <module>
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\test_deque.py", line 808, in test_main
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1812, in run_unittest
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1787, in _run_suite
test.support.TestFailed: Traceback (most recent call last):
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\test_deque.py", line 671, in test_weakref
    self.assertRaises(ReferenceError, str, p)
AssertionError: ReferenceError not raised by str
```

```
Error Message:
 Traceback (most recent call last):
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\test_deque.py", line 825, in <module>
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\test_deque.py", line 808, in test_main
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1812, in run_unittest
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1787, in _run_suite
test.support.TestFailed: Traceback (most recent call last):
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\test_deque.py", line 537, in test_container_iterator
    self.assertTrue(ref() is None, "Cycle was not collected")
AssertionError: False is not true : Cycle was not collected
```

**Comment by slozier** [comment]
test_dictcomp
---
```
Error Message:
 Traceback (most recent call last):
  File "R:\Documents\Programming-github\ironpython3\Tests\test_dictcomp.py", line 102, in <module>
  File "R:\Documents\Programming-github\ironpython3\bin\Release\net45\Lib\iptest\ipunittest.py", line 356, in run_test
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1812, in run_unittest
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1787, in _run_suite
test.support.TestFailed: Traceback (most recent call last):
  File "R:\Documents\Programming-github\ironpython3\Tests\test_dictcomp.py", line 91, in test_scope_mixing_closures
    r = {k:k for k in eval(lambda i: range(i+v), v)}
  File "R:\Documents\Programming-github\ironpython3\Tests\test_dictcomp.py", line 86, in eval
    return f(i)
  File "R:\Documents\Programming-github\ironpython3\Tests\test_dictcomp.py", line 91, in <lambda$1>
    r = {k:k for k in eval(lambda i: range(i+v), v)}
TypeError: unsupported operand type(s) for +: 'int' and 'DictCompTest'
```

test_setcomp
---
```
Error Message:
 Traceback (most recent call last):
  File "R:\Documents\Programming-github\ironpython3\Tests\test_setcomp.py", line 102, in <module>
  File "R:\Documents\Programming-github\ironpython3\bin\Release\net45\Lib\iptest\ipunittest.py", line 356, in run_test
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1812, in run_unittest
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1787, in _run_suite
test.support.TestFailed: Traceback (most recent call last):
  File "R:\Documents\Programming-github\ironpython3\Tests\test_setcomp.py", line 91, in test_scope_mixing_closures
    r = {k for k in eval(lambda i: range(i+v), v)}
  File "R:\Documents\Programming-github\ironpython3\Tests\test_setcomp.py", line 86, in eval
    return f(i)
  File "R:\Documents\Programming-github\ironpython3\Tests\test_setcomp.py", line 91, in <lambda$1>
    r = {k for k in eval(lambda i: range(i+v), v)}
TypeError: unsupported operand type(s) for +: 'int' and 'SetCompTest'
```

**Comment by slozier** [comment]
test_regressions
---
```
Failed   netcoreapp2.1.IronPython.test_regressions
Error Message:
 Traceback (most recent call last):
  File "R:\Documents\Programming-github\ironpython3\Tests\test_regressions.py", line 1365, in <module>
  File "R:\Documents\Programming-github\ironpython3\bin\Release\netcoreapp2.1\Lib\iptest\ipunittest.py", line 356, in run_test
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1812, in run_unittest
  File "R:\Documents\Programming-github\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1787, in _run_suite
test.support.TestFailed: Traceback (most recent call last):
  File "R:\Documents\Programming-github\ironpython3\Tests\test_regressions.py", line 1080, in test_ipy2_gh273
    self.assertEqual(A.cnt, 0)
AssertionError: 1 != 0
```

**Comment by slozier** [comment]
Also `IronPython.test_strformat` although I haven't been able to pinpoint the issue since it doesn't fail when run alone without IsolationLevel.

**Comment by slozier** [comment]
In `AllCPython.test_file` we get a weakref failure in `AutoFileTests.testWeakRefs`.

**Comment by slozier** [comment]
Also `AllCPython.test_array` in `BaseTest.test_weakref`.
