### ISSUE TITLE
Defining a class with a metaclass can raise a TypeError

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#854]
From `test_metaclass_abc` in `CPython.test_abc`:
```Python
class test(type):
    def __instancecheck__(cls, instance):
        subtype = type(instance)
        return cls.__subclasscheck__(subtype)
    def __subclasscheck__(cls, subclass):
        return False

class A(metaclass=test):
    pass

class meta(type, A):
    def x(self):
        return 1

class C(metaclass=meta):
    pass
```
raises a `TypeError`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in __instancecheck__
TypeError: __subclasscheck__() takes exactly 2 arguments (1 given)
```

**Comment by slozier** [comment]
Closing since https://github.com/IronLanguages/ironpython3/pull/855 gets the above passing. However, I'm not sure if the underlying issue is resolved.
