### ISSUE TITLE
Failure in test_collections during CI

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#925]
Saw the following failure during CI for netcoreapp2.1.CPython.test_collections:
```
FAILED (errors=1)
  X netcoreapp2.1.CPython.test_collections [3s 239ms]
  Error Message:
   Traceback (most recent call last):
  File "D:\a\ironpython3\ironpython3\Src\StdLib\Lib\test\test_collections.py", line 1293, in test_main
  File "D:\a\ironpython3\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1812, in run_unittest
  File "D:\a\ironpython3\ironpython3\Src\StdLib\Lib\test\support\__init__.py", line 1787, in _run_suite
  File "D:\a\ironpython3\ironpython3\Src\StdLib\Lib\test\test_collections.py", line 1298, in <module>
test.support.TestFailed: Traceback (most recent call last):
  File "D:\a\ironpython3\ironpython3\Src\StdLib\Lib\test\test_collections.py", line 313, in test_pickle
    q = loads(dumps(p, protocol))
  File "D:\a\ironpython3\ironpython3\Src\StdLib\Lib\pickle.py", line 1558, in _loads
    return _Unpickler(file, fix_imports=fix_imports,
  File "D:\a\ironpython3\ironpython3\Src\StdLib\Lib\pickle.py", line 1041, in load
    dispatch[key[0]](self)
  File "D:\a\ironpython3\ironpython3\Src\StdLib\Lib\pickle.py", line 1336, in load_global
    klass = self.find_class(module, name)
  File "D:\a\ironpython3\ironpython3\Src\StdLib\Lib\pickle.py", line 1386, in find_class
    __import__(module, level=0)
ImportError: No module named 'copy_reg'
```

**Comment by slozier** [comment]
Occured again on Windows net46.test_collections.
